version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  api-proxy:
    build:
      context: ./api-proxy
    container_name: api-proxy
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis

  heartbeat-service:
    build:
      context: ./heartbeat-service
    container_name: heartbeat-service
    depends_on:
      - api-proxy
      - redis
